---
- name: Deploy Python Web App to Remote Machine
  hosts: webservers
  become: yes
  tasks:
    - name: Install Python3 and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Create application directory
      file:
        path: /opt/webapp
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy Python app to remote machine
      copy:
        src: ./app.py
        dest: /opt/webapp/app.py
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Create systemd service file
      copy:
        dest: /etc/systemd/system/webapp.service
        content: |
          [Unit]
          Description=Python Web Application
          After=network.target

          [Service]
          Type=simple
          User={{ ansible_user }}
          WorkingDirectory=/opt/webapp
          ExecStart=/usr/bin/python3 /opt/webapp/app.py
          Restart=always
          RestartSec=3

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start webapp service
      systemd:
        name: webapp
        state: restarted
        enabled: yes

    - name: Allow port 8001 through firewall (if UFW is active)
      ufw:
        rule: allow
        port: '8001'
        proto: tcp
      ignore_errors: yes

    - name: Display success message
      debug:
        msg: "Web app deployed successfully! Access it at http://192.168.1.28:8001"
